from PyQt5 import QtCore, QtGui, QtWidgets
import sys
sys.path.append("../") # 返回上层路径
from service import service
import tkinter as tk
from tkinter import messagebox
from PyQt5.QtCore import QDate,   QDateTime , QTime
#import plot8p3

class Ui_Dialog(object):
    def __init__(self):
        super(Ui_Dialog, self).__init__()
        self.setWindowFlags(QtCore.Qt.MSWindowsFixedSizeDialogHint)  # 只显示最小化和关闭按钮

        
        self.setupUi(self) # 初始化窗体设置
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(918, 715)
        #self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        #self.buttonBox.setGeometry(QtCore.QRect(370, 680, 341, 32))
        #self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        #self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        #self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 180, 891, 451))
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 891, 451))
        self.groupBox.setObjectName("groupBox")


        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(460, 680, 91, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnExit = QtWidgets.QPushButton(Dialog)
        self.btnExit.setGeometry(QtCore.QRect(800, 680, 91, 32))
        self.btnExit.setObjectName("btnExit")
        self.btnAnaly = QtWidgets.QPushButton(Dialog)
        self.btnAnaly.setGeometry(QtCore.QRect(530, 680, 91, 32))
        self.btnAnaly.setObjectName("btnAnaly")
        self.btnSave = QtWidgets.QPushButton(Dialog)
        self.btnSave.setGeometry(QtCore.QRect(620, 680, 91, 32))
        self.btnSave.setObjectName("btnSave")
        self.btnPrint = QtWidgets.QPushButton(Dialog)
        self.btnPrint.setGeometry(QtCore.QRect(710, 680, 91, 32))
        self.btnPrint.setObjectName("Print")
        self.editName = QtWidgets.QTextEdit(Dialog)
        self.editName.setGeometry(QtCore.QRect(50, 640, 640, 36))
        self.editName.setObjectName("editName")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 650, 25, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")


        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.editName_1 = QtWidgets.QLineEdit(Dialog)
        self.editName_1.setGeometry(QtCore.QRect(70, 20, 141, 20))
        self.editName_1.setObjectName("editName_1")
        self.editName_2 = QtWidgets.QLineEdit(Dialog)
        self.editName_2.setGeometry(QtCore.QRect(70, 50, 141, 20))
        self.editName_2.setObjectName("editName_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(220, 50, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(QDateTime.currentDateTime(),Dialog)
        self.dateTimeEdit.setGeometry(QtCore.QRect(270, 50, 135, 32))
        self.dateTimeEdit.setObjectName("bdateTimeEdit")
        self.dateTimeEdit.setDisplayFormat("yyyy-MM-dd HH:mm:ss")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(415, 50, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.editName_3 = QtWidgets.QLineEdit(Dialog)
        self.editName_3.setGeometry(QtCore.QRect(467, 50, 80, 20))
        self.editName_3.setObjectName("editName_3")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(550, 53, 25, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(220, 20, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.editName_4 = QtWidgets.QLineEdit(Dialog)
        self.editName_4.setGeometry(QtCore.QRect(270, 20, 280, 20))
        self.editName_4.setObjectName("editName_4")
        self.btnSelect = QtWidgets.QPushButton(Dialog)
        self.btnSelect.setGeometry(QtCore.QRect(550, 15, 45, 32))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnSelect.setFont(font)
        self.btnSelect.setObjectName("Select")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 88, 350, 85))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(360, 88, 350, 85))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 110, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.editName_5 = QtWidgets.QLineEdit(Dialog)
        self.editName_5.setGeometry(QtCore.QRect(75, 110, 70, 20))
        self.editName_5.setObjectName("editName_5")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(150, 110, 25, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(20, 140, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.editName_6 = QtWidgets.QLineEdit(Dialog)
        self.editName_6.setGeometry(QtCore.QRect(75, 140, 70, 20))
        self.editName_6.setObjectName("editName_6")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(150, 140, 25, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(175, 110, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.editName_6 = QtWidgets.QLineEdit(Dialog)
        self.editName_6.setGeometry(QtCore.QRect(215, 110, 70, 20))
        self.editName_6.setObjectName("editName_6")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(290, 115, 25, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(170, 140, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.editName_7 = QtWidgets.QLineEdit(Dialog)
        self.editName_7.setGeometry(QtCore.QRect(220, 140, 70, 20))
        self.editName_7.setObjectName("editName_7")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(290, 145, 25, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(370, 110, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.editName_15 = QtWidgets.QLineEdit(Dialog)
        self.editName_15.setGeometry(QtCore.QRect(425, 110, 70, 20))
        self.editName_15.setObjectName("editName_15")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(500, 110, 25, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(370, 140, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.editName_16 = QtWidgets.QLineEdit(Dialog)
        self.editName_16.setGeometry(QtCore.QRect(425, 140, 70, 20))
        self.editName_16.setObjectName("editName_16")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(500, 140, 25, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(525, 110, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.editName_26 = QtWidgets.QLineEdit(Dialog)
        self.editName_26.setGeometry(QtCore.QRect(565, 110, 70, 20))
        self.editName_26.setObjectName("editName_26")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(640, 115, 25, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(525, 140, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.editName_27 = QtWidgets.QLineEdit(Dialog)
        self.editName_27.setGeometry(QtCore.QRect(570, 140, 70, 20))
        self.editName_27.setObjectName("editName_27")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(642, 145, 25, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.retranslateUi(Dialog)
        #self.buttonBox.accepted.connect(Dialog.accept)
        #self.buttonBox.rejected.connect(Dialog.reject)
        #self.buttonBox.accepted.connect(self.exit)
        #self.buttonBox.rejected.connect(self.exit)
        #self.btnAdd.clicked.connect(self.add) # 绑定添加按钮的单击信号
        self.btnExit.clicked.connect(self.exit) # 绑定添加按钮的单击信号
        self.btnAnaly.clicked.connect(self.add) # 绑定添加按钮的单击信号
        self.btnSave.clicked.connect(self.add) # 绑定添加按钮的单击信号
        self.btnPrint.clicked.connect(self.add) # 绑定添加按钮的单击信号  
        self.btnSelect.clicked.connect(self.getInfo)

        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def exit(self):
        sys.exit()

    def add(self):
        root = tk.Tk()
        root.withdraw()
        messagebox.showinfo('my messagebox', 'hello world')
        #self.zoom()


    def getInfo(self):
        file =  QtWidgets.QFileDialog()  # 创建文件对话框
        file.setDirectory('C:\\')  # 设置初始路径为C盘
        if file.exec_():  # 判断是否选择了文件
            filename=file.selectedFiles()[0] # 获取选择的文件
            self.editName_4.setText(filename)# 将选择的文件显示在文本框中
            
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "圖形顯示"))
        self.label_2.setText(_translate("Dialog", "開始檢測："))
        self.btnAnaly.setText(_translate("Dialog", "分析"))
        self.btnSave.setText(_translate("Dialog", "存檔"))
        self.btnPrint.setText(_translate("Dialog", "列印"))
        self.btnExit.setText(_translate("Dialog", "離開"))
        self.label_3.setText(_translate("Dialog", "備註"))
        self.label_4.setText(_translate("Dialog", "操作人員:"))
        self.label_5.setText(_translate("Dialog", "連接埠:"))
        self.label_6.setText(_translate("Dialog", "測試日期:"))
        self.label_7.setText(_translate("Dialog", "檢測時間:"))
        self.label_8.setText(_translate("Dialog", "分鐘"))
        self.label_9.setText(_translate("Dialog", "選擇檔案:"))
        self.btnSelect.setText(_translate("Dialog", "選擇"))
        self.groupBox_2.setTitle(_translate("Dialog", "通道0")) 
        self.groupBox_3.setTitle(_translate("Dialog", "通道1"))
        self.label_10.setText(_translate("Dialog", "設定位準:"))
        self.label_11.setText(_translate("Dialog", "mV"))
        self.label_12.setText(_translate("Dialog", "最大幅值:"))
        self.label_13.setText(_translate("Dialog", "mV"))
        self.label_14.setText(_translate("Dialog", "資料數 :"))
        self.label_15.setText(_translate("Dialog", "筆"))
        self.label_16.setText(_translate("Dialog", "最大頻率:"))
        self.label_17.setText(_translate("Dialog", "MHz"))
        self.label_20.setText(_translate("Dialog", "設定位準:"))
        self.label_21.setText(_translate("Dialog", "mV"))
        self.label_22.setText(_translate("Dialog", "最大幅值:"))
        self.label_23.setText(_translate("Dialog", "mV"))
        self.label_24.setText(_translate("Dialog", "資料數 :"))
        self.label_25.setText(_translate("Dialog", "筆"))
        self.label_26.setText(_translate("Dialog", "最大頻率:"))
        self.label_27.setText(_translate("Dialog", "MHz"))
       # self.editName.setPlainText(_translate("Dialog", "備註"))
       # self.label_3.setText(_translate("Dialog", "密  码："))
       # self.btnLogin.setText(_translate("Dialog", "登录"))
       # self.btnExit.setText(_translate("Dialog", "退出"))
